# Generated by Django 5.2.5 on 2025-08-10 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField()),
                ('status', models.CharField(default='queued', max_length=50)),
                ('bot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bots.bot')),
            ],
        ),
    ]
